server:
  port: 80

spring:
  application:
    name: cloud-consumer-order

  # consul注册中心的配置
  cloud:
    consul:
      host: 192.168.253.128
      port: 8500
      discovery:
        #暴露服务名称
        service-name: ${spring.application.name}