server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YoungDawnGE/SpringCloudStudy.git # Github上面的git仓库名字
          # 在远程仓库的搜索目录
          search-paths:
            - a-springcloud-config/config-file
          # 读取的分支
      label: master

# 服务注册到eureka的地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版