server:
  port: 8004

spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gyc
    password: GYCgyc123???
    url: jdbc:mysql://192.168.253.128:3306/springcloud2020

  # zookeeper的配置
  cloud:
    zookeeper:
      connect-string: 192.168.253.128:2181


mybatis:
  type-aliases-package: com.gyc.springcloud.entity
  mapper-locations: classpath:mapper/*.xml
