server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider

  #nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.253.128:8848

#actuator监控
management:
  endpoints:
    web:
      exposure:
        include: '*'