server:
  port: 83
spring:
  application:
    name: nacos-order-consumer

  # nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.253.128:8848

#消费者将要去访问的微服务名称(注册进nacos的微服务提供者) 这个地方可以不配置 是写给自己用的
server-url:
  nacos-user-service: http://nacos-payment-provider
